# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28224174c21b03676fd6956ba02cd91181887e772f1b1ac530e7d3d8ddced207a78c8e361209f85329731b4e953e0061613c3a974d91376c763a2782e8da8bf9

test:
  secret_key_base: c6b4e9362a2e7250964c2c913f1138a975fca35bd1807b3d477480a83b589803e076e2e66d208c9ae035299991b40a7a11a39a84049b7341aa952ac86d06b8b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
